language: julia

os:
    - linux
    - osx

julia:
    - 0.5
    #- nightly

notifications:
    email: false

before_script:
  - export PATH=$HOME/.local/bin:$PATH

install:
  #- sudo pip install pymdown-extensions

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("PDFExtract"); Pkg.test("PDFExtract"; coverage=true)'

after_success:
  #- julia -e 'Pkg.add("Documenter")'
  #- julia -e 'cd(Pkg.dir("PDFExtract")); include(joinpath("docs", "make.jl"))'
